# Generated by Django 5.0.2 on 2024-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
