# Generated by Django 5.0.2 on 2024-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_versionhistory_notes_versionhistory_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionhistory',
            name='notes',
            field=models.JSONField(default=dict),
        ),
    ]
