# Generated by Django 5.0.2 on 2024-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_versionhistory_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionhistory',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
