# Generated by Django 5.0.2 on 2024-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_versionhistory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionhistory',
            name='notes',
            field=models.JSONField(default=list),
        ),
    ]
