# Generated by Django 5.0.2 on 2024-02-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_versionhistory_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.JSONField(default=list)),
            ],
        ),
    ]
